version: "3.9"  # optional since v1.27.0
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=CONNECTION_STRING_HIDDEN/?retryWrites=true&w=majority
      - MONGO_DB_NAME=CloudAssignment
      - REDIS_URI=rediss://default:CONNECTION_STRING_HIDDEN
